

service: hakaton-back
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  timeout: 28 # optional, in seconds, default is 6  
  httpApi:
    payload: '2.0'
    cors: true
   
functions:
  app:
    handler: serverLamda.handler
    events:
      - httpApi: "*"